apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/provider-type: community
  name: git-update-deployment
spec:
  description: This Task can be used to update image digest in a Git repo using kustomize.
    It requires a secret with credentials for accessing the git repo.
  params:
  - name: GIT_REPOSITORY
    type: string
  - name: GIT_REF
    type: string
    default: "main"
  - name: NEW_IMAGE
    type: string
  - name: NEW_DIGEST
    type: string
  - name: KUSTOMIZATION_PATH
    type: string
  - name: CREATE_BRANCH_NAME
    type: string
    default: "skip"
  results:
  - description: The commit SHA
    name: commit
    type: string
  steps:
  - image: docker.io/alpine/git:v2.26.2
    name: git-clone
    resources: {}
    script: |
      rm -rf git-update-digest-workdir

      echo "Cloning $(params.GIT_REPOSITORY) $(params.GIT_REF)"

      git clone -v $(params.GIT_REPOSITORY) -b $(params.GIT_REF) git-update-digest-workdir

      if [ "$(params.CREATE_BRANCH_NAME)" = "skip" ]
      then
        echo "Skip branching"
      else
        cd git-update-digest-workdir
        git checkout -b $(params.CREATE_BRANCH_NAME)
      fi
    workingDir: $(workspaces.workspace.path)
  - image: quay.io/wpernath/kustomize-ubi:latest
    name: update-digest
    resources: {}
    script: |
      cd git-update-digest-workdir/$(params.KUSTOMIZATION_PATH)
      kustomize edit set image $(params.NEW_IMAGE)@$(params.NEW_DIGEST)

      echo "##########################"
      echo "### kustomization.yaml ###"
      echo "##########################"
      cat kustomization.yaml
    workingDir: $(workspaces.workspace.path)
  - image: docker.io/alpine/git:v2.26.2
    name: git-commit
    resources: {}
    script: |
      cd git-update-digest-workdir

      git config user.email "tektonbot@redhat.com"
      git config user.name "My Tekton Bot"

      git status
      git add $(params.KUSTOMIZATION_PATH)/kustomization.yaml
      git commit -m "[ci] Image digest updated"

      if [ "$(params.CREATE_BRANCH_NAME)" = "skip" ]
      then
        git push
      else
        git push origin HEAD:$(params.CREATE_BRANCH_NAME)
      fi

      RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
      EXIT_CODE="$?"
      if [ "$EXIT_CODE" != 0 ]
      then
        exit $EXIT_CODE
      fi
      # Make sure we don't add a trailing newline to the result!
      echo -n "$RESULT_SHA" > $(results.commit.path)
    workingDir: $(workspaces.workspace.path)
  workspaces:
  - description: The workspace consisting of maven project.
    name: workspace
