---
- hosts: localhost
  connection: local
  vars:
    ansible_remote_tmp: /runner/.ansible/tmp

    gitea_username: user1
    gitea_url: http://gitea:3000
    #gitea_url: https://gitea-gitea.apps.cluster-bcc29.bcc29.sandbox167.opentlc.com

    webhooks:
      - repo: inventory-quarkus
        url: https://el-inventory-coolstore-cicd.{{ sub_domain }}
      - repo: gateway-vertx
        url: https://el-gateway-coolstore-cicd.{{ sub_domain }}
      - repo: catalog-spring-boot
        url: https://el-catalog-coolstore-cicd.{{ sub_domain }}
      - repo: web-nodejs
        url: https://el-web-coolstore-cicd.{{ sub_domain }}
      - repo: coolstore
        url: https://openshift-gitops-server-openshift-gitops.{{ sub_domain }}/api/webhook

  tasks:

    - name: Use username/password
      set_fact:
        authorization: "Basic {{ (gitea_username + ':' + gitea_password) | b64encode }}"

    - name: Create WebHooks in Gitea
      uri:
        url: "{{ gitea_url}}/api/v1/repos/{{ gitea_username }}/{{ item.repo }}/hooks"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body:
          active: true
          branch_filter: "*"
          config:
            content_type: "json"
            url: "{{ item.url }}"
          events:
            - "push"
          type: "gitea"
        status_code: [201, 400]
      with_items: "{{ webhooks }}"

    - name:  Set default branch of coolstore repo
      uri:
        url: "{{ gitea_url}}/api/v1/repos/{{ gitea_username }}/coolstore"
        method: PATCH
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body:
          default_branch: "main"
        status_code: [200]