apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/coolstore-demo/inventory-quarkus.git'
  name: inventory-quarkus
  labels:
    app: inventory-quarkus
    app.kubernetes.io/component: inventory-quarkus
    app.kubernetes.io/instance: inventory-quarkus
    app.kubernetes.io/name: inventory-quarkus
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-quarkus
  template:
    metadata:
      labels:
        app: inventory-quarkus
    spec:
      containers:
      - name: inventory-quarkus
        image: quay.io/coolstore-demo/inventory-quarkus:1.0.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
